# Generated by Django 3.2.10 on 2021-12-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zero_waste_app', '0006_rename_products_productinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'permissions': (('can_add_new_product', 'Add new product'), ('can_add_existing_product', 'Add product'), ('can_delete_product', 'Delete product'))},
        ),
    ]
