# Generated by Django 3.2.10 on 2021-12-12 20:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zero_waste_app', '0004_auto_20211212_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductList',
            new_name='Products',
        ),
    ]
