# Generated by Django 3.2.10 on 2021-12-12 21:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zero_waste_app', '0005_rename_productlist_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ProductInstance',
        ),
    ]
