# Generated by Django 3.2.9 on 2021-12-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zero_waste_app', '0007_alter_productinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={},
        ),
    ]
