# Generated by Django 3.2.9 on 2022-01-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zero_waste_app', '0011_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zero_waste_app.product'),
        ),
    ]
