# Generated by Django 3.2.9 on 2022-01-08 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zero_waste_app', '0012_alter_productinstance_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInstance',
            new_name='UserProduct',
        ),
    ]
