INSERT INTO zero_waste_app_product(name)
VALUES ('cebula'),
       ('czosnek'),
       ('puszka pomidorów'),
       ('bazylia'),
       ('pieprz'),
       ('śmietana'),
       ('cytryna'),
       ('sucha ciecierzyca'),
       ('soda oczyszczona'),
       ('liście laurowe'),
       ('tahina (pasta sezamowa)'),
       ('różowa sól himalajska'),
       ('płatki papryczki chili'),
       ('oliwa z oliwek'),
       ('gotowe ciasto do pizzy'),
       ('wegańska śmietana'),
       ('gotowany burak'),
       ('ser feta'),
       ('łuskany słonecznik'),
       ('sól'),
       ('piersi kurczaka'),
       ('mąka pszenna'),
       ('śmietana 30%'),
       ('masło'),
       ('parmezan'),
       ('bulion drobiowy'),
       ('świeża bazylia'),
       ('zielone pesto'),
       ('świeże kurki'),
       ('czerwona papryka'),
       ('ogórki kiszone'),
       ('wędzona papryka'),
       ('koncentrat pomidorowy'),
       ('ziele angielskie'),
       ('liść laurowy'),
       ('bulion warzywny'),
       ('mąka ziemniaczana'),
       ('natka pietruszki'),
       ('zimna woda'),
       ('pieprz czarny mielony'),
       ('duża cukinia'),
       ('mielone siemię lniane'),
       ('gorąca woda'),
       ('mąka kukurydziana'),
       ('proszek do pieczenia'),
       ('świeży koperek'),
       ('cebula dymka'),
       ('mleko'),
       ('jajko'),
       ('jabłka'),
       ('masło orzechowe'),
       ('cukier'),
       ('groch łuskany, zielony'),
       ('kasza manna'),
       ('kminek'),
       ('kurkuma'),
       ('curry'),
       ('limonka'),
       ('szpinak baby'),
       ('marchew'),
       ('ziemniaki'),
       ('mielona wędzona papryka'),
       ('płatki chili'),
       ('śmietana 18%'),
       ('bulion'),
       ('bakłażan'),
       ('marchewka'),
       ('mała cebula'),
       ('musztarda Dijon'),
       ('olej rzepakowy'),
       ('świeża mięta'),
       ('serek śmietankowy'),
       ('pomidor'),
       ('boczek'),
       ('jajka'),
       ('tortilla pszenna'),
       ('pieprz cayenne'),
       ('makaron spaghetti'),
       ('sos pomidorowy'),
       ('sardele'),
       ('kapary'),
       ('czarne oliwki'),
       ('papryczki chili w zalewie z oliwy'),
       ('ser pecorino'),
       ('świeże oregano'),
       ('makaron razowy penne'),
       ('ser gorgonzola'),
       ('szalotka'),
       ('brokuł'),
       ('czerwona cebula'),
       ('słodka papryka mielona'),
       ('wędzona słodka papryka'),
       ('ostra papryczka'),
       ('makaron casarecce lub penne'),
       ('świeży szczypiorek'),
       ('majonez'),
       ('musztarda'),
       ('cukier waniliowy'),
       ('cukier puder'),
       ('cynamon'),
       ('domowa konfitura'),
       ('chleb'),
       ('masło klarowane'),
       ('miód'),
       ('kardamon'),
       ('imbir'),
       ('gałka muszkatołowa'),
       ('żurawina'),
       ('ryż');

INSERT INTO zero_waste_app_recipe(name, instructions)
VALUES ('Sos pomidorowo-śmietanowy', 'Na patelni rozgrzać olej. Wrzucić pokrojoną cebulę i chwilę podsmażać aż się zeszkli. Dodać posiekany czosnek i smarzyć kilka chwil. Wrzucić pomidory, bazylię i pieprz. Gotować ok 10 min. aż pomidory nie będą miękkie a sos zgęstnieje. Dodać śmietanę i gotować ok. 5-8 minut. Doprawić do smaku.'),
       ('Twarożek ze szczypiorkiem',  'Twaróg rozgnieść/rozdrobnić widelcem w misce. Dodać kilka łyżeczek jogurtu, tyle żeby łatwo można było go rozsmarowywać, ale nie był bardzo rzadki. Szczypiorek posiekać i dodać do twarogu, posypać lekko solą, zostawić na chwilę i później całość wymieszać. Doprawić pieprzem i solą do smaku.'),
       ('Humus z tahiną i płatkami chili', 'W dużej misce z dużą ilością wody mocz przez całą noc ciecierzycę z dodatkiem 1 łyżeczki sody oczyszczonej.
Namoczoną wcześniej ciecierzycę opłukujemy dużą ilością wody na sitku. Przekładamy do garnka, dodajemy liście laurowe i resztę sody. Gotujemy do miękkości (ok. 40-50 minut) na średnim ogniu, uważając, aby całość nie wykipiała. Co jakiś czas zbieramy białą pianę łyżką cedzakową.
Po ugotowaniu usuwamy liście laurowe, odsączamy ciecierzycę, przekładamy do dużej miski i odstawiamy do przestudzenia.
2 łyżki ciecierzycy pozostawiamy do ozdobienia talerza. Resztę przekładamy do blendera. Dodajemy tahinę, sok z cytryny, obrane ząbki czosnku i sól. Blendujemy do momentu uzyskania kremowej konsystencji. Pod koniec blendowania dodajemy wodę, tak aby całość była gładka i jedwabista. Wszystko może potrwać ok. 15 minut.
Humus przekładamy do miski. Dekorujemy płatkami chili, ciecierzycą i oliwą.'),
       ('Pizza rolls z burakami i fetą', 'Śmietanę mieszamy w miseczce z przeciśniętymi przez praskę ząbkami czosnku, solą i pieprzem.
Ciasto na pizzę rozwijamy i smarujemy śmietaną z czosnkiem. Buraka, pokrojonego w bardzo cienkie talarki, układamy na śmietanie. Całość oprószamy fetą oraz słonecznikiem. Skrapiamy oliwą.
Ciasto zwijamy wzdłuż dłuższego boku. Powstały rulon kroimy na osiem równych kawałków. Rollsy układamy obok siebie, zwinięciem do góry, w foremce wyłożonej papierem do pieczenia. Pieczemy przez 20 minut w piekarniku rozgrzanym do temperatury 200°C.'),
       ('Kurczak w sosie pesto', 'Piersi kurczaka przekrawamy wzdłuż na pół tak, by powstały 4 filety. Mięso oprószamy solą i pieprzem, a następnie obtaczamy w mące. 
Na patelni na rozgrzanej oliwie obsmażamy piersi kurczaka na złoty kolor. Mięso przekładamy na ciepły półmisek i przykrywamy folią aluminiową.
Na tej samej patelni rozpuszczamy masło. Dodajemy mąkę, mieszamy i chwilę smażymy, aż mąka lekko się zarumieni - w ten sposób powstanie zasmażka. Dodajemy śmietanę i bulion. Doprawiamy solą i pieprzem. Mieszamy. Gotujemy ok. 5 minut, aż sos zgęstnieje.
Dodajemy parmezan starty na tarce o drobnych oczkach i zielone pesto. Dokładnie mieszamy i gotujemy jeszcze kilka minut. Do sosu pesto przekładamy usmażonego wcześniej kurczaka i gotujemy całość ok. 5 minut. Patelnię zdejmujemy z ognia. Kurczaka dekorujemy listkami świeżej bazylii.
Kurczaka w sosie pesto możemy podawać z ryżem, makaronem lub gnocchi.'),
       ('Pasta z bakłażana i marchewki', 'Marchewki obieramy i kroimy w talarki o grubości ok. 1 cm, marynujemy w 1 łyżce oleju. Dodajemy pokrojony w plasterki czosnek. Warzywa zawijamy w folię aluminiową i pieczemy w piekarniku rozgrzanym do 180°C przez 30 minut.
Paprykę smarujemy olejem. Bakłażana kroimy w plastry o grubości 2 cm, a cebulę w cienkie plastry. Warzywa układamy na blasze do pieczenia, dokładamy paprykę w całości. Skrapiamy pozostałym olejem. Dokładamy warzywa do piekącej się marchewki – bakłażana pieczemy 20 minut aż do zbrązowienia, paprykę – tak długo, aż popęka skórka.
Paprykę obieramy ze skóry i usuwamy gniazda nasienne. Miąższ papryki wraz z pozostałymi warzywami przekładamy do naczynia blendera. Miksujemy na gładką masę. Doprawiamy musztardą i pieprzem. Podajemy z chlebem lub serem feta i listkami mięty.'),
       ('Tortilla z jajkiem i bekonem', 'Zioła myjemy, listki obrywamy i siekamy. Mieszamy z serkiem śmietankowym i skórką otartą z limonki oraz odrobiną soku z limonki, doprawiamy solą i pieprzem cayenne.
Pomidora oczyszczamy i kroimy w cienkie plasterki. Bekon smażymy na patelni, aż będzie chrupiący, odstawiamy. Masło rozpuszczamy na patelni, podsmażamy na nim krótko z obu stron plasterki pomidora. Jajka rozbijamy i dodajemy do pomidora, smażymy sadzone.
Tortille, jedną po drugiej, podgrzewamy przez chwilę na suchej patelni, aż będą elastyczne. Smarujemy serkiem śmietankowym i posypujemy bekonem. Na każdej układamy po 2 jajka sadzone z pomidorami, lekko solimy i natychmiast podajemy.'),
       ('Spaghetti alla puttanesca', 'Cebulę i czosnek kroimy w plasterki i smażymy na oliwie z oliwek do ich zeszklenia. Drobno siekamy sardele i papryczki chili, czarne oliwki kroimy w plasterki.
Na patelnię dodajemy sos pomidorowy, sardele, kapary nonpareilles i czarne oliwki. Doprawiamy solą i papryczkami chili.
Makaron spaghetti gotujemy we wrzącej, osolonej wodzie zgodnie z instrukcją na opakowaniu, odcedzamy na durszlaku i łączymy z sosem. Z wierzchu oprószamy serem pecorino startym na wiórki. Makaron podajemy udekorowany świeżym oregano.'),
       ('Wegański strogonow z kurek', 'Kurki przekładamy do dużej miski i obficie oprószamy mąką pszenną. Dokładnie mieszamy, by mąka pokryła wszystkie grzyby, zwłaszcza od strony blaszek. Całość zalewamy zimną wodą. Woda powinna w całości przykryć kurki. Delikatnie mieszamy grzyby dłonią, by pozbyć się piasku i zanieczyszczeń, które opadną na dno miski razem z mąką.
Kurki przekładamy partiami na sitko i dokładnie opłukujemy pod bieżącą wodą. Oczyszczone grzyby osuszamy na ręczniku papierowym.
Cebulę pokrojoną w kostkę smażymy na patelni na rozgrzanej oliwie. Gdy się zeszkli, dodajemy kurki pokrojone na mniejsze, podłużne kawałki. Małe kurki dodajemy na patelnię w całości. Smażymy, mieszając, aż się zarumienią.
Do usmażonych kurek dodajemy drobno posiekany czosnek, paprykę pokrojoną w paski i ogórki pokrojone w słupki. Doprawiamy wędzoną papryką, zielem angielskim i liściem laurowym. Dodajemy koncentrat pomidorowy. Mieszamy i przesmażamy, aż smaki i składniki się połączą.
Całość zalewamy połową bulionu warzywnego. Wegański strogonow dusimy ok. 5-10 minut, tak by warzywa lekko zmiękły, ale wciąż pozostały lekko chrupiące. Pod koniec duszenia doprawiamy solą i pieprzem.
Mąkę ziemniaczaną łączymy w szklance z drugą połową bulionu. Mieszamy. Tak przygotowaną miksturę wlewamy do strogonowa, cały czas mieszając danie. Gotujemy chwilę, aż strogonow zgęstnieje.
Dodajemy wegańską śmietanę. Całość posypujemy posiekaną natką pietruszki.'),
       ('Wegańskie placki z cukinii', 'Cukinię ścieramy na tarce o grubych oczkach i przekładamy na sitko. Odsączamy z nadmiaru soku i przekładamy do miski. Posypujemy solą. Mieszamy, ponownie mocno odciskamy sok, a startą cukinię przedkładamy do osobnej miski.
Siemię lniane przesypujemy do miseczki, zalewamy gorącą wodą i odstawiamy.
Do startej i odsączonej cukinii na tarce o drobnych oczkach ścieramy czosnek. Dodajemy oba rodzaje mąki, proszek do pieczenia, namoczone siemię lniane, posiekany koperek, szczypiorek z dymki i pieprz. Całość dokładnie mieszamy.
Na rozgrzaną patelnię wlewamy oliwę. Nakładamy po 1 łyżce ciasta i delikatnie rozpłaszczamy je z wierzchu. Placki smażymy na złoty kolor z obu stron. Po zdjęciu z patelni odsączamy z nadmiaru tłuszczu na ręcznikach papierowych.'),
       ('Pancakes faszerowane jabłkiem', 'Masło i mleko dajemy do rondelka. Podgrzewamy do momentu rozpuszczenia masła. Zdejmujemy z ognia i odstawiamy do krótkiego przestudzenia. 
Mąkę, proszek do pieczenia, sól i cukier łączymy w misce.
Jajko wbijamy do rondelka z mlekiem i masłem. Całość dokładnie mieszamy i przelewamy do miski z suchymi składnikami. Całość mieszamy do momentu uzyskania jednolitej masy.
Jabłka obieramy, usuwamy gniazda nasienne i kroimy na plastry o grubości 0,5 cm.
Jeden plaster jabłka smarujemy masłem orzechowym i przykrywamy kolejnym plastrem jabłka. Czynność powtarzamy w przypadku pozostałych plastrów. Jabłka obtaczamy z obu stron w cieście.
Oliwę rozgrzewamy na patelni i smażymy jabłka obtoczone w cieście.'),
       ('Kotleciki z grochu ze szpinakiem', 'Groch przełóż do dużej miski, zalej zimną wodą i dokładnie wypłucz. Czynność powtórz kilka razy, aż woda po płukaniu grochu będzie przejrzysta. Umyty groch ponownie zalej zimną wodą (tak, by przykrywała ona nasiona w całości) i odstaw na ok. 2-3 godziny, a najlepiej na całą noc.
Wodę, w której moczyliśmy groch, odlewamy, a groch przekładamy do garnka. Zalewamy zimną wodą (tak, by jej poziom był ok. 2 cm wyższy niż poziom nasion – groch nie potrzebuje dużych ilości wody), doprawiamy solą i kminkiem, zagotowujemy. Zmniejszamy ogień.
Groch gotujemy, często mieszając, ok. 40-50 minut, aż nasiona wchłoną wodę, zmiękną i zaczną się rozpadać. W razie potrzeby – jeśli woda wyparuje szybciej, a groch wciąż będzie twardy – podlewamy go niewielkimi ilościami wody.
Ugotowany groch odstawiamy do wystudzenia.
Na patelni, na rozgrzanej oliwie smażymy cebulę pokrojoną w drobną kostkę. Gdy się zeszkli, dodajemy czosnek przeciśnięty przez praskę. Smażymy chwilę, mieszając. Dodajemy szpinak i blanszujemy, aż jego liście zmniejszą swoją objętość. Odstawiamy do wystudzenia.
Wystudzony groch przekładamy do miski i blendujemy na gładkie, jednolite purée. Dodajemy zawartość patelni, jajko, kaszę mannę i przyprawy. Mieszamy. Zwilżamy dłonie wodą i z masy formujemy niewielkie kulki, które następnie lekko spłaszczamy i wyrównujemy po bokach, formując kształtne kotleciki.
Uformowane kotleciki smażymy z obu stron na patelni, na rozgrzanej oliwie, aż się zarumienią. Po usmażeniu odsączamy z nadmiaru oliwy na papierowym ręczniku. Usmażone kotleciki podajemy ze świeżym szpinakiem, cząstkami limonki i ulubionym sosem.'),
       ('Kremowa grochówka z curry', 'Groch przełóż do dużej miski, zalej zimną wodą i dokładnie wypłucz. Czynność powtórz kilka razy, aż woda po płukaniu grochu będzie przejrzysta. Umyty groch ponownie zalej zimną wodą (tak, by przykrywała ona nasiona w całości) i odstaw na ok. 2-3 godziny, a najlepiej na całą noc.
Wodę, w której moczyliśmy groch odlewamy, a groch przekładamy do garnka. Zalewamy zimną wodą (tak, by jej poziom był ok. 2 cm wyższy niż poziom nasion – groch nie potrzebuje dużych ilości wody), doprawiamy solą. Zagotowujemy i zmniejszamy ogień.
Groch gotujemy, często mieszając, ok. 40-50 minut, aż nasiona wchłoną wodę, zmiękną i zaczną się rozpadać. W razie potrzeby – jeśli woda wyparuje szybciej, a groch wciąż będzie twardy – podlewamy go niewielkimi ilościami wody.
Ugotowany groch odstawiamy do wystudzenia.
W dużym garnku, na rozgrzanej oliwie smażymy cebulę pokrojoną w kostkę. Gdy się zeszkli, dodajemy czosnek pokrojony w plasterki. Smażymy, mieszając. Dodajemy marchewkę i ziemniaki pokrojone w kostkę. Smażymy, aż warzywa lekko się zarumienią (nie muszą mięknąć w trakcie smażenia, ponieważ będą gotowane w zupie).
Całość doprawiamy curry i wędzoną papryką. Mieszamy i smażymy chwilę razem, by przyprawy połączyły się z warzywami i oddały aromaty pod wpływem ciepła.
Warzywa zalewamy bulionem. Zagotowujemy, zmniejszamy ogień i gotujemy ok. 20 minut, aż ziemniaki i marchewka zmiękną.
Dodajemy ugotowany groch, mieszamy i miksujemy całość za pomocą blendera na gładką, jednolitą zupę krem. Doprawiamy solą i pieprzem, ewentualnie – ponownie curry i wędzoną papryką.
Jeśli zupa okaże się zbyt gęsta, rozcieńczamy ją odrobiną wody lub bulionu. Kremową grochówkę przelewamy do miseczek. Podajemy z kleksem śmietany. Z wierzchu posypujemy płatkami chili i dekorujemy natką pietruszki.'),
       ('Makaron razowy z sosem serowo-brokułowym', 'Makaron gotujemy zgodnie z instrukcją na opakowaniu. Różyczki brokułu blanszujemy w gorącej wodzie.
Szalotkę kroimy w drobne piórka. Na patelnię wlewamy oliwę i rozgrzewamy. Podsmażamy szalotkę. Gorgonzolę kroimy w kostkę, dodajemy na patelnię wraz ze śmietaną. Podsmażamy aż do rozpuszczenia sera.
Zblanszowane różyczki brokułu dodajemy do sosu. Doprawiamy solą i pieprzem. Sos skrapiamy sokiem wyciśniętym z połowy limonki. Dodajemy makaron i mieszamy.'),
       ('Wegański makaron z sosem z pieczonej papryki', 'Paprykę kroimy w ćwiartki i pozbawiamy gniazd nasiennych. Układamy na blasze wyłożonej papierem do pieczenia razem z cebulą pokrojoną w ćwiartki i ząbkami czosnku. Warzywa skrapiamy oliwą.
Pieczemy ok. 20 minut w piekarniku rozgrzanym do temperatury 200°C.
Podpieczone warzywa łączymy w naczyniu blendera lub rozdrabniacza ze śmietaną, słodką i wędzoną papryką oraz pieprzem. Miksujemy na gładki, jednolity sos.
Makaron gotujemy w osolonej wodzie według wskazówek umieszczonych na opakowaniu. Przelewamy zimną wodą i odcedzamy na durszlaku. Po odcedzeniu przekładamy do garnka, w którym się gotował.
Makaron zalewamy sosem z pieczonych warzyw. Mieszamy. Przekładamy na talerze i dekorujemy posiekaną ostrą papryczką lub listkami świeżej bazylii.'),
       ('Domowa pasta jajeczna', 'Jajka gotujemy na twardo, studzimy w zimnej wodzie, obieramy i ścieramy do miski na tarce o dużych oczkach.
Dodajemy posiekany szczypiorek, musztardę i majonez. Doprawiamy solą i pieprzem. Mieszamy. Jeśli pasta jest zbyt sucha, dodajemy 1 łyżkę majonezu i ponownie mieszamy.'),
       ('Tosty w jajku', 'Jajka z mlekiem roztrzepujemy dokładnie, dodając szczyptę soli. Jeśli do tostów używamy chałki, to do masy mleczno-jajecznej dodajemy jeszcze cukier waniliowy.
Na patelni rozgrzewamy masło, każdą kromkę maczamy w masie (większe kromki przekrawamy na pół) i układamy na rozgrzanym tłuszczu. Smażymy z obu stron na rumiano, wykładamy na ręcznik papierowy.
Tosty z chałki posypujemy przed podaniem chmurką cukru pudru z cynamonem, albo podajemy z ulubioną konfiturą.'),
       ('Korzenny pudding ryżowy', 'Ryż gotujemy zgodnie z instrukcją na opakowaniu. Gdy będzie gotowy, zostawiamy trochę wody w garnku i dodajemy mleko. Zmniejszamy gaz i gotujemy ok. 3-5 minut.
Do ryżu dodajemy żurawinę oraz przyprawy. Gotujemy pod przykryciem ok. 3-5 minut, uważając, aby nie przypalić ryżu. Gotowy pudding przekładamy do miseczek i polewamy miodem.');


INSERT INTO INSERT INTO zero_waste_app_recipeingredient(amount, ingredient_id, recipe_id, unit)
VALUES (   1,   1, 1, 'szt.'),
       (   2,   2, 1, 'ząbki'),
       (   1,   3, 1, 'szt.'),
       (  10,   4, 1, 'listków'),
       (   1,   5, 1, 'łyżeczka'),
       ( 150,   6, 1, 'ml'),
       (   1,  16, 4, 'szt.'),
       ( 150,  17, 4, 'g'),
       (   2,   2, 4, 'ząbki'),
       (   1,  18, 4, 'szt.'),
       ( 100,  19, 4, 'g'),
       (   2,  20, 4, 'łyżki'),
       (   1,  15, 4, 'łyżka'),
       ( 0.5,  21, 4, 'łyżeczki'),
       ( 0.5,   5, 4, 'łyżeczki'),
       ( 400,   8, 3, 'g'),
       (   2,   9, 3, 'łyżeczki'),
       (   2,  10, 3, 'szt.'),
       ( 100,  11, 3, 'g'),
       (   4,   2, 3, 'ząbki'),
       ( 0.5,  12, 3, 'łyżeczki'),
       ( 120,  13, 3, 'ml'),
       (   1,  14, 3, 'łyżeczka'),
       (   4,  15, 3, 'łyżki'),
       ( 0.5,   7, 3, 'szt.'),
       (   2,  22, 6, 'szt.'),
       (   1,  23, 6, 'łyżka'),
       (   1,  15, 6, 'szt.'),
       ( 300,  24, 6, 'ml'),
       (0.75,  25, 6, 'szklanki'),
       (   1,  26, 6, 'łyżka'),
       (   1,   2, 6, 'ząbek'),
       ( 160,  27, 6, 'g'),
       (   1,  28, 6, 'garść'),
       ( 0.5,  29, 6, 'szklanki'), 
       ( 0.5,  21, 6, 'łyżeczki'),
       ( 0.5,   5, 6, 'łyżeczki'),
       ( 400,  30, 7, 'g'),
       (   1,   1, 7, 'szt.'),
       (   2,  15, 7, 'łyżki'),
       (   1,  31, 7, 'szt.'),
       (   3,  32, 7, 'szt.'),
       (   1,   2, 7, 'ząbek'),
       (   1,  33, 7, 'łyżeczka'),
       (   1,  34, 7, 'łyżka'),
       (   3,  35, 7, 'szt.'),
       (   1,  36, 7, 'szt.'),
       ( 250,  37, 7, 'ml'),
       (   1,  21, 7, 'szczypta'),
       (   1,  38, 7, 'łyżka'),
       ( 0.5,  39, 7, 'pęczka'),
       ( 400,  23, 7, 'g'),
       (   1,  40, 7, 'l'),
       (   1,  41, 7, 'szczypta'),
       (   3,  17, 7, 'łyżki'),
       (   1,  42, 8, 'szt.'),
       (   1,  21, 8, 'łyżeczka'),
       (   2,  43, 8, 'łyżki'),
       (   5,  44, 8, 'łyżek'),
       (   2,   2, 8, 'ząbki'),
       ( 0.5,  23, 8, 'szklanki'),
       (0.25,  45, 8, 'szklanki'),
       (   1,  46, 8, 'łyżeczka'),
       (   1,  47, 8, 'pęczek'),
       (   1,  48, 8, 'pęczek'),
       (   1,  41, 8, 'szczypta'),
       (   3,  15, 8, 'łyżki'),
       (   3,  26, 9, 'łyżki'),
       (0.25,  49, 9, 'szklanki'),
       ( 0.5,  23, 9, 'szklanki'),
       (   2,  46, 9, 'łyżeczki'),
       (   1,  50, 9, 'szt.'),
       (   4,  51, 9, 'szt.'),
       ( 0.5,  52, 9, 'szklanki'),
       (   2,  15, 9, 'łyżki'),
       (  25,  53, 9, 'g'),
       (   1,  21, 9, 'szczypta'),
       ( 250,  58, 12, 'g'),
       (   2,  59, 12, 'łyżki'),
       (   1,  60, 12, 'szczypta'),
       (   1,   1, 12, 'szt.'),
       (   2,   2, 12, 'ząbki'),
       (   1,  50, 12, 'szt.'),
       (   1,  21, 12, 'szczypta'),
       (   1,  41, 12, 'szczypta'),
       ( 0.5,  61, 12, 'łyżeczki'),
       ( 0.5,  62, 12, 'łyżeczki'),
       (   1,  63, 12, 'szt.'),
       (   3,  15, 12, 'łyżki'),
       (   7,  64, 12, 'listków'),
       ( 200,  58, 13, 'g'),
       (   2,  65, 13, 'szt.'),
       (   3,  66, 13, 'szt.'),
       (   1,   1, 13, 'szt.'),
       (   3,   2, 13, 'ząbki'),
       (   1,  62, 13, 'łyżeczka'),
       (   1,  67, 13, 'łyżeczka'),
       (  10,  68, 13, 'g'),
       ( 100,  69, 13, 'g'),
       (   4,  15, 13, 'łyżki'),
       (   1,  21, 13, 'łyżeczka'),
       (   1,   5, 13, 'łyżeczka'),
       (  10,  39, 13, 'listków'),
       (   2,  70, 13, 'l'),
       (   1,  71, 14, 'szt.'),
       (   2,  72, 14, 'szt.'),
       (   1,  31, 14, 'szt.'),
       (   2,   2, 14, 'ząbki'),
       (   1,  73, 14, 'szt.'),
       (   1,  74, 14, 'łyżeczka'),
       (   2,  75, 14, 'łyżki'),
       (   1,   5, 14, 'łyżeczka'),
       (   4,  81, 16, 'łodygi'),
       (0.25,  39, 16, 'pęczka'),
       ( 150,  82, 16, 'g'),
       ( 0.5,  63, 16, 'szt.'),
       (   1,  83, 16, 'szt.'),
       (   8,  84, 16, 'plastrów'),
       (   8,  85, 16, 'szt.'),
       (   4,  86, 16, 'szt.'),
       ( 0.5,  21, 16, 'łyżeczki'),
       (   3,  26, 16, 'łyżki'),
       (   1,  87, 16, 'szczypta'),
       ( 500,  88, 17, 'g'),
       ( 350,  89, 17, 'g'),
       (   1,   1, 17, 'szt.'),
       (   2,   2, 17, 'ząbki'),
       (  30,  90, 17, 'g'),
       (  30,  91, 17, 'g'),
       (   3,  92, 17, 'łyżki'),
       (   1,  93, 17, 'łyżka'),
       (  40,  94, 17, 'g'),
       (   3,  15, 17, 'łyżki'),
       (   1,  95, 17, 'mały'),
       ( 400,  98, 19, 'g'),
       ( 100,  99, 19, 'g'),
       ( 400,  69, 19, 'g'),
       (   1, 100, 19, 'szt.'),
       ( 0.5,  63, 19, 'szt.'),
       (   6, 101, 19, 'różyczek'),
       ( 0.5,  21, 19, 'łyżeczki'),
       ( 0.5,   5, 19, 'łyżeczki'),
       (   3,  31, 20, 'szt.'),
       (   1, 102, 20, 'szt.'),
       (   3,   2, 20, 'ząbki'),
       ( 200,  17, 20, 'g'),
       (   1, 103, 20, 'łyżeczka'),
       ( 0.5, 104, 20, 'łyżeczki'),
       ( 0.5,  21, 20, 'łyżeczki'),
       (0.25,  41, 20, 'łyżeczki'),
       (   3,  15, 20, 'łyżki'),
       (   1, 105, 20, 'szt.'),
       ( 180, 106, 20, 'g'),
       (  10,  85, 21, 'szt.'),
       ( 0.5, 107, 21, 'pęczka'),
       (   2, 108, 21, 'łyżki'),
       (   1, 109, 21, 'łyżeczka'),
       (   1,  21, 21, 'szczypta'),
       (   1,   5, 21, 'szczypta'),
       (   4,  85, 22, 'szt.'),
       (   1,  21, 22, 'szczypta'),
       (   2, 110, 22, 'łyżeczki'),
       (   2, 111, 22, 'łyżki'),
       ( 0.5, 112, 22, 'łyżeczki'),
       (   1, 113, 22, 'szt.'),
       ( 0.5,  49, 22, 'szklanki'),
       (   2, 114, 22, 'kromki'),
       (   1, 115, 22, 'łyżka'),
       (   1, 116, 23, 'łyżka'),
       (   1, 112, 23, 'łyżeczka'),
       ( 0.5, 117, 23, 'łyżeczki'),
       (0.25, 118, 23, 'łyżeczki'),
       (0.25, 119, 23, 'łyżeczki'),
       (   1, 120, 23, 'garść'),
       (   1,  21, 23, 'szczypta'),
       ( 600,  49, 23, 'ml'),
       ( 100, 121, 23, 'g');